=== rakita-08/WebTech/XML/test.xsd
<?xml version="1.0" encoding="UTF-8"?>

<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

  <xs:element name="students">
    <xs:complexType>
      <xs:sequence>
        
        <xs:element name="student" maxOccurs="unbounded">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="id" type="xs:int"/>
              <xs:element name="name" type="xs:string"/>
              <xs:element name="department" type="xs:string"/>
            </xs:sequence>
          </xs:complexType>
        </xs:element>

      </xs:sequence>
    </xs:complexType>
  </xs:element>

</xs:schema>

=== rakita-08/WebTech/XML/test.xml
<?xml version="1.0" encoding="UTF-8"?>

<students xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
          xsi:noNamespaceSchemaLocation="test.xsd">

    <student>
        <id>101</id>
        <name>Mimi</name>
        <department>CSIT</department>
    </student>

    <student>
        <id>102</id>
        <name>Rakee</name>
        <department>IT</department>
    </student>

</students>
